### PR TITLE
Add μPD78c10A Datasheet

### PR DESCRIPTION
**Pull request by birdybro**
Another NEC chip on the motherboard for the PC-FX apparently.

### CODE REVIEW

**Comment by dshadoff** [comment]
Are you sure this chip is on the board ?  I hadn't heard of it before...

**Comment by birdybro** [comment]
It seems to be one of the ones here as I was looking at the daughterboard. 

https://commons.wikimedia.org/wiki/File:NEC-PC-FX-Daughterboard-Flat.jpg

**Comment by dshadoff** [comment]
OK, it's there... but I don't know what it does...
I'll accept this, but I'm going to move the datasheets to their own folder.

**Comment by birdybro** [comment]
Yup, that makes sense!

**Pull request merged**
